#!/usr/bin/env perl
# vim:ft=perl
use strict;
use warnings;

my @data;
while (<>) {
	chomp;
	my ($cc, $a, $b, $n, $bday, $owner) = split /,/;
	my ($dd, $mm, $yy) = split '/', $bday;
	push @data, {
		cc    => $cc || '',
		start => $a,
		end   => $b,
		n     => $n,
		bday  => $bday,
		yy    => $yy,
		mm    => $mm,
		dd    => $dd,
		yyyy  => ($yy > 50 ? $yy + 1900 : $yy + 2000),
		mmdd  => "$mm/$dd",
		owner => $owner,
	};
}

my $n = 32;
my %maskable = map { $_ => $n-- } qw(
	1
	2
	4
	8
	16
	32
	64
	128
	256
	512
	1024
	2048
	4096
	8192
	65536
	16384
	32768
	262144
	524288
	1048576
	2097152
	4194304
	8388608
	16777216
	33554432
	67108864
	134217728
	268435456
	536870912
	1073741824
	2147483648
);
for (grep { $maskable{$_->{n}} } @data) {
	print "INSERT INTO ranges (network, mask, n, birthday, country)\n";
	print "  VALUES ('$_->{start}', $maskable{$_->{n}}, $_->{n}, '$_->{yyyy}-$_->{mm}-$_->{dd}'::date, '$_->{cc}')\n";
	print "  ON CONFLICT (network) DO NOTHING;\n\n";
}
